import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    TextInput: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        width: '85%',
        padding: 14,
        marginBottom: 12,
        fontSize: 16,
        color: '#000000',
        alignSelf: "center",
        height: 50,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },

    TextInputArea: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        width: '85%',
        padding: 14,
        marginBottom: 12,
        textAlignVertical: 'top',
        alignSelf: "center",
        height: 100,
        fontSize: 16,
        color: '#000000',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },

    Picker: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        width: '85%',
        paddingHorizontal: 14,
        marginBottom: 12,
        alignSelf: "center",
        height: 50,
        justifyContent: "center",
        color: '#000000',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },

    PickerRow: {
        backgroundColor: '#ffffff',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        width: 150,
        paddingHorizontal: 12,
        marginBottom: 8,
        alignSelf: "center",
        height: 48,
        justifyContent: "center",
        marginHorizontal: 6,
        color: '#000000',
    },

    Button: {
        backgroundColor: '#9b59b6',
        borderRadius: 25,
        width: '70%',
        alignSelf: "center",
        justifyContent: "center",
        alignItems: "center",
        marginTop: 24,
        marginBottom: 24,
        height: 55,
        shadowColor: '#9b59b6',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },

    ButtonText: {
        fontSize: 18,
        color: '#ffffff',
        fontWeight: '600',
        letterSpacing: 0.5,
    },

    TitleInputs: {
        fontSize: 16,
        color: "#000000",
        marginLeft: 28,
        marginTop: 12,
        marginBottom: 6,
        fontWeight: '600',
    },
    
    TitleInputsRow: {
        fontSize: 15,
        color: "#000000",
        marginLeft: 12,
        marginTop: 12,
        fontWeight: '500',
        marginBottom: 4,
    },

    BackButton: {
        position: 'absolute',
        left: 16,
        alignItems: "center",
        justifyContent: "center",
        top: 12,
        backgroundColor: 'rgba(0,0,0,0.05)',
        borderRadius: 30,
        width: 40,
        height: 40,
        zIndex: 10,
    },

    BackButtonText: {
        fontSize: 16,
        color: '#000000',
        marginLeft: 8,
        marginBottom: 0,
        alignSelf: "center",
        fontWeight: '500',
    },

    SexoAndCivil: {
        flexDirection: 'row',
        alignSelf: "center",
        justifyContent: 'space-around',
        width: '85%',
        marginVertical: 8,
        gap: 12,
    },

    Title: {
        alignSelf: "center",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 16,
        marginTop: 8,
    },

    TitleText: {
        fontSize: 24,
        color: '#000000',
        fontWeight: 'bold',
        letterSpacing: 0.8,
    },

    Header: {
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        paddingBottom: 12,
        marginBottom: 16,
        width: '90%',
        flexDirection: 'row',
        alignSelf: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'transparent',
    },

    pickDate: {
        backgroundColor: '#ffffff',
        paddingHorizontal: 14,
        width: '85%',
        borderRadius: 12,
        alignItems: "center",
        borderColor: '#e0e0e0',
        borderWidth: 1,
        justifyContent: "center",
        alignSelf: "center",
        flexDirection: 'row',
        height: 50,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },

    date: {
        fontSize: 15,
        color: '#000000',
        alignSelf: "center",
        fontWeight: '500',
    },

    logo: {
        width: '80%',
        height: 110,
        alignSelf: "center",
        marginTop: 24,
        marginBottom: 8,
        resizeMode: 'contain',
    },
});